Nginx

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # [SENSITIF] Ganti nama domain asli Anda
    server_name <DOMAIN_ANDA>;

    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location /hls {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
        
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length';

        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }
        
        alias /var/www/html/hls; 
    }
}